
#spring.datasource.driverClassName: org.mariadb.jdbc.Driver
spring.datasource.driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.url: jdbc:mariadb://61.109.249.21:13306/fla_platform_db
spring.datasource.url: jdbc:log4jdbc:mariadb://localhost:3306/board
spring.datasource.username: root
spring.datasource.password: 1234


spring:
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: none
    #      SQL: DEBUG
    show-sql: false
    properties.hibernate.format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secretKey: root